services:
  app:
    build: .
    volumes:
      - .:/app  # This connects your Windows folder to the Linux container
    ports:
      - "8000:8000"
      - "8501:8501"
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8000 & 
             streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0"